// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myLibrary.Models;

namespace myLibrary.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20181031141348_MyMigration")]
    partial class MyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("myLibrary.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<string>("NameAuthor");

                    b.Property<int>("YearBirth");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Россия",
                            NameAuthor = "Пушкин Александр Сергеевич",
                            YearBirth = 1799
                        },
                        new
                        {
                            Id = 2,
                            Country = "Россия",
                            NameAuthor = "Лермонтов Михаил Юрьевич",
                            YearBirth = 1838
                        },
                        new
                        {
                            Id = 3,
                            Country = "Россия",
                            NameAuthor = "Булгаков Михаил Афанасьевич",
                            YearBirth = 1891
                        });
                });

            modelBuilder.Entity("myLibrary.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<int>("CountPage");

                    b.Property<string>("NameBook");

                    b.Property<string>("Publisher");

                    b.Property<int>("YearPublish");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CountPage = 160,
                            NameBook = "Капитанская дочька",
                            Publisher = "НИГМА",
                            YearPublish = 1836
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            CountPage = 24,
                            NameBook = "Полтава",
                            Publisher = "Художественный фонд",
                            YearPublish = 1829
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            CountPage = 224,
                            NameBook = "Герой нашего времени",
                            Publisher = "Азбука",
                            YearPublish = 1985
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            CountPage = 480,
                            NameBook = "Мастер и Маргарита",
                            Publisher = "Азбука",
                            YearPublish = 1960
                        });
                });

            modelBuilder.Entity("myLibrary.Models.Book", b =>
                {
                    b.HasOne("myLibrary.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
